diffusion:
  pretrained_first_stage_model_path: stabilityai/sd-vae-ft-ema
  transport:
    path_type: Linear
    prediction: velocity
    loss_weight: null
    sample_eps: null
    train_eps: null
    snr_type: lognorm
  sampler:
    mode: ODE
    sde:
      sampling_method: Euler
      diffusion_form: sigma
      diffusion_norm: 1.0
      last_step: Mean
      last_step_size: 0.04
    ode:
      sampling_method: dopri5
      atol: 1.0e-06
      rtol: 0.001
      reverse: false
      likelihood: false
  network_config:
    target: fit.model.fit_model.FiT
    params:
      context_size: 1024
      patch_size: 2
      in_channels: 4
      hidden_size: 2304
      depth: 40
      num_heads: 24
      mlp_ratio: 4.0
      class_dropout_prob: 0.1
      num_classes: 1000
      learn_sigma: false
      use_sit: true
      use_checkpoint: true
      use_swiglu: true
      use_swiglu_large: false
      q_norm: layernorm
      k_norm: layernorm
      qk_norm_weight: false
      rel_pos_embed: rope
      custom_freqs: ntk-aware
      decouple: true
      ori_max_pe_len: 16
      online_rope: true
      abs_pos_embed: null
      adaln_type: lora
      adaln_lora_dim: 576
      
