resolution: 256
seed:
  global_seed: 999
precision:
  tf32: true   # By default, use TF32 matmuls (recommended for Ampere GPUs)
network_config:
    target: fit.model.bfm.FiT
    params:
      context_size: 32
      patch_size: 2
      in_channels: 4
      hidden_size: 384
      depth: 24
      num_heads: 6
      mlp_ratio: 4.0
      class_dropout_prob: 0.1
      num_classes: 1000
      learn_sigma: false
      use_sit: true
      use_swiglu: false
      use_swiglu_large: false
      use_checkpoint: false
      q_norm: RMSNorm
      k_norm: RMSNorm
      qk_norm_weight: false
      rel_pos_embed: rope
      abs_pos_embed: null
      adaln_type: normal
      adaln_lora_dim: 96
      number_of_perflow: 6
      edm_sigmas: false
      overlap: false
      number_of_representation_blocks: 6
      representation_align: false
      n_patch_h: 16
      n_patch_w: 16

autoencoder:
  path: "/nfs/dogyun/vae-flux/"
  
sampling:
  per_proc_batch_size: 25
  num_fid_samples: 50000
  # Sampling-related hyperparameters
  mode: "sde"
  path_type: "linear"       # choices: [linear, cosine]
  num_steps: 250
  heun: false               # Only for ODE
  guidance_low: 0.0
  guidance_high: 1.0