diffusion:
  pretrained_first_stage_model_path: stabilityai/sd-vae-ft-ema
  improved_diffusion:
    timestep_respacing: ''
    noise_schedule: linear
    use_kl: false
    sigma_small: false
    predict_xstart: false
    learn_sigma: true
    rescale_learned_sigmas: false
    diffusion_steps: 1000
  noise_scheduler:
    num_train_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: linear
    prediction_type: epsilon
    steps_offset: 0
    clip_sample: false
  network_config:
    target: fit.model.fit_model.FiT
    params:
      context_size: 256
      patch_size: 2
      in_channels: 4
      hidden_size: 1152
      depth: 28
      num_heads: 16
      mlp_ratio: 4.0
      class_dropout_prob: 0.1
      num_classes: 1000
      learn_sigma: true
      use_swiglu: true
      use_swiglu_large: true
      use_xToken: false
      rel_pos_embed: rope
      abs_pos_embed: null